# Generated by Django 3.0.5 on 2020-12-13 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appoinment',
            old_name='doctor',
            new_name='Doctor',
        ),
        migrations.RenameField(
            model_name='appoinment',
            old_name='patient',
            new_name='Patient',
        ),
    ]
